# Generated by Django 3.1.7 on 2021-06-13 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadfiles',
            name='phn',
            field=models.CharField(max_length=12),
        ),
    ]
